=== LHansbauer/XmlMemory/A1B2.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT spiel (karten*,spieler*,zustand)>
<!ELEMENT karten EMPTY>
<!ATTLIST karten 
aufgedeckt (yes|no) "no" 
kartenzustand (offen|geschlossen) "geschlossen"
id ID #REQUIRED
>
<!ELEMENT spieler (gewonnenekarten*,anzahlaufgedeckter)>
<!ATTLIST spieler name ID #REQUIRED
 punkte CDATA #REQUIRED>
<!ELEMENT gewonnenekarten EMPTY>
<!ATTLIST gewonnenekarten gew IDREF #REQUIRED >
<!ELEMENT anzahlaufgedeckter (#PCDATA)>
<!ELEMENT zustand (offene*,geschlossene*,istDran)>
<!ATTLIST zustand lÃ¤uftSpiel (yes|no) "yes">
<!ELEMENT offene EMPTY>
<!ATTLIST offene off IDREF #REQUIRED >
<!ELEMENT geschlossene EMPTY>
<!ATTLIST geschlossene ges IDREF #REQUIRED >
<!ELEMENT istDran EMPTY>
<!ATTLIST istDran ist IDREF #REQUIRED >

=== LHansbauer/XmlMemory/A1B2_xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE spiel SYSTEM "A1B2.dtd">
<spiel>
    <karten aufgedeckt="yes" id="t_1" kartenzustand="offen"/>
    <karten id="t_2" aufgedeckt="yes" kartenzustand="offen"/>
    <karten id ="t_3" aufgedeckt="no" kartenzustand="geschlossen"/>
    <spieler name="p_1" punkte="2">
        <gewonnenekarten gew="t_1" />
        <gewonnenekarten gew="t_2"/>
        <anzahlaufgedeckter>2</anzahlaufgedeckter>
    </spieler>
    <spieler name="p_2" punkte="0">
        <anzahlaufgedeckter>0</anzahlaufgedeckter>
    </spieler>
    <zustand lÃ¤uftSpiel="yes">
        <offene off="t_1"/>
        <offene off="t_2"/>
        <geschlossene ges="t_3"/>
        <istDran ist="p_2"/>
    </zustand>
</spiel>
